shrey141102/Javascript-projects

README.md, Temperature Converter/README.md, Temperature Converter/demo.js, Temperature Converter/index.html, Temperature Converter/style.css
=> Added the Temperature converter project by Parmesh B

BMI calculator/README.md, BMI calculator/index.html, BMI calculator/script.js, BMI calculator/style.css, README.md
Added new BMI calculator project
=> Added BMI calculator

Happy Birthday wisher/HBD.html, Happy Birthday wisher/README.md
=> Added Happy Birthday Wisher

Micro Code Editor in the Browser/index.html, Micro Code Editor in the Browser/readme.md, Micro Code Editor in the Browser/script.js, Micro Code Editor in the Browser/style.css, README.md
=> Added Micro Editor in Browser

README.md, Stopwatch/README.md, Stopwatch/index.html, Stopwatch/script.js, Stopwatch/style.css
=> Added Stopwatch project

Rock Paper Scissor/README.md, Rock Paper Scissor/index.html, Rock Paper Scissor/script.js, Rock Paper Scissor/style.css
=> Added Rock paper scissor game

Quote Generate/README.md, Quote Generate/index.html, Quote Generate/script.js, Quote Generate/styles.css, README.md, script.js
Added Quotes Generator and linked it to main website.
=> Added Quotes Generator

README.md, URL Shortener/README.md, URL Shortener/index.html, URL Shortener/script.js, URL Shortener/style.css
Added the files for URL Shortener
Closes issue #42
=> Add URL Shortener

Analog Clock/README.md, Analog Clock/index.html, Analog Clock/script.js, Analog Clock/styles.css, README.md, script.js
Created a cool analog clock and linked it to the main project
=> Analog Clock

Tic Tac Toe/README.md, Tic Tac Toe/index.html, Tic Tac Toe/script.js, Tic Tac Toe/style.css, script.js
created a tic tac toe game using html, css & js and linked to the main project file
=> Tic Tac Toe

README.md, script.js, weatherApplication/index.css, weatherApplication/index.html, weatherApplication/index.js, weatherApplication/readme.md
issue no: (https://github.com/shrey141102/Javascript-projects/issues/50)
=> Added Weather App issue:#50

To-Do/script.js
Added the functionality in todo application now u can see it when u refresh or reopen the site it never disaper it save in localstorage and the application is running smoth u can also check whether the list is saving on the localstorage or not by going to application throough doing insecpt and go to localstorage
=> update the saving list in localstorage part

JavaScript Hangman Game project/index.html, JavaScript Hangman Game project/readme.md, JavaScript Hangman Game project/script.js, JavaScript Hangman Game project/style.css, script.js
=> added Javascript Hangman Game

Note Taking Application/index.html, Note Taking Application/script.js, Note Taking Application/style.css, Palindrome Checker/index.html, Palindrome Checker/script.js, Palindrome Checker/style.css, script.js
=> Added note taking application and updated main script.js

Temperature Converter/demo.js, Temperature Converter/index.html, Temperature Converter/style.css
I have modified all three files for better functionality and representation
demo.js: 21022a00d03a9f111beb81426c0db2300ed813c0
index.html: b9e23cf8c4a33875c7948db0bb38bdf84f4b5d81
style.css: 5c9838aa2f30e16d000bb3dee44320b721f5415a
=> Updated Temperature Converter

README.md, Word Scramble/index.html, Word Scramble/readme.md, Word Scramble/script.js, Word Scramble/style.css, script.js
Created read me file for the word scramble game
- [y ] I have performed a self-review of my code
- [ y] If it is a new project, I have added thorough tests.
- [ y] Have you updated the README file of the repository and added the name of the project in it?
- [ y] Have you added a `README.md` file inside the directory of your project and explained it there properly?
=> Created readme.md

script.js
=> fixed card images and typos 

Random Joke Generator/README.md, Random Joke Generator/index.html, Random Joke Generator/script.js, Random Joke Generator/style.css
=> Random Joke Generator

index.html, script.js, style.css
I have added a scroll to top button which appears when scrolled down, and on click take to projects section. 
#130
=> Scroll to top button

Image_Generator_App/README.md, Image_Generator_App/index.html, Image_Generator_App/index.js, Image_Generator_App/style.css
=> Uploaded html and README file

Temperature Converter/style.css, Tic Tac Toe/script.js
Updated the game by adding winning and drawing, along with winning lines in case of win.
5d22d40bd252ccc18afe960853c2e01a87c73eef
=> #144 issue: Update Tic-Tac-Toe

Maze Generator App/Readme.md, Maze Generator App/index.html, Maze Generator App/script.js, Maze Generator App/style.css
- [y ] I have performed a self-review of my code
- [y ] If it is a new project, I have done thorough tests.
- [ y] Have you updated the README file of the repository and added the name of the project in it?
- [ y] Have you added a `README.md` file inside the directory of your project and explained it there properly (with images)?
- [ y] Have you updated the `script.js` file so that the project is visible in the website?
=> Maze-Generator

README.md, Weight-Converter/index.html, Weight-Converter/readme.md, Weight-Converter/script.js, Weight-Converter/styles.css, script.js
Added a weight converter that supports conversion between various common units
#147
=> Added Weight Converter

Memory Game of Tiles/README.md, README.md, script.js
I have added documentation to Memory game and also included it into the main website.
=> Added documentation

script.js
- Chess game not deploy on the Javascript projects file but in my repo chess game working properly
- Have a look: https://mehul237.github.io/Chess-Game/
=> Problem in chess game

ScrollReveal.js, index.html
Fixes #174 
**The website , when scrolled , reveals it's elements one by one in a systematic way.** 
```
ScrollReveal({
reset: true,
distance: "40px",
duration: 2000,
});
ScrollReveal().reveal(".banner__title,.heading,.social,.footerTitle", {
delay: 200,
origin: "top",
});
ScrollReveal().reveal(".banner__text,.cards__item", {
delay: 300,
origin: "top",
distance: "50px",
});
```
Here , the rules of the effect are specified such as delay , distance , origin and so on. We have to mention the class name inside the `ScrollReveal().reveal(" { enter class name }",)` part.
For cusstomisation of the rules, simply copy this section and paste in the next line and modify the rules according, along with different classnames ( it is reccommended not to have different rules for same element. ) …
=> Added Scroll Reveal Effect to the main website

style.css
Modified "style.css" file.
1. Pointer Cursor:
Applied a pointer cursor effect when hovering over card elements.
2. Zoom Effect using Transform Property:
Implemented a smooth zoom effect on the cards utilizing the CSS transform property.
fixes #201 
- [Yes] I have performed a self-review of my code
- [Y] If it is a new project, I have done thorough tests.
- [Y] Have you updated the README file of the repository and added the name of the project in it?
- [Y] Have you added a `README.md` file inside the directory of your project and explained it there properly (with images)?
- [Y] Have you updated the `script.js` file so that the project is visible in the website?
P.S-> "IT IS NOT A NEW PROJECT HENCE DIDN'T IMPLY WITH THE LAST CHECKPOINTS". I had to add a "Y" as I was getting a error by …
=> added hover and zoom effect

Factorial-Calculator/README.md, Factorial-Calculator/index.html, Factorial-Calculator/script.js, Factorial-Calculator/style.css, script.js
- Factorial project is ready.
- This project can calculate factorial of the very large numbers.
closes #200
=> [KWOC] Factorial Calculator Project Ready
